version: '3'

services: 

  cassandra:
    image: cassandra:3.11
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
      - cassandra-data:/home/cassandra/.cassandra
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  test_app:
    build: .
    image: test_app:0.1.0
    # environment:
    # - PORT=9999
    # - CONSUL_HTTP_ADDR=192.168.88.188:8500
    restart: always
    ports:
      - "5555:5555"
    # links:
    #   - cassandra
    # depends_on:
    #   - "cassandra"

  proxy:
    image: nginx:latest
    ports: 
      - "80:80" # host:container
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # connect host's ./nginx.conf with container's nginx.conf
      # :ro == read only perms in container
    # depends_on:
    #   - test_app
    # links:
    #   - test_app

volumes:
  cassandra-data: {}