version: '3'

services: 
  cassandra:
    build:
      context: .
      dockerfile: Dockerfile_cassandra
    image: modified_cassandra:3.11
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-data:/var/lib/cassandra
      - ./cassandra-data:/home/cassandra/.cassandra
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  test_app:
    build: .
    image: test_app:0.1.0
    restart: always
    ports:
      - "5555:5555"

  proxy:
    image: nginx:latest
    ports: 
      - "80:80" # host:container
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  cassandra-data: {}